CREATE SCHEMA IF NOT EXISTS tds;

CREATE TABLE IF NOT EXISTS tds.users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    emailId VARCHAR(255) NOT NULL UNIQUE,  -- Keep as emailId
    role VARCHAR(50) NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT false
);